### ISSUE TITLE
Prod not working

### ISSUE THREAD

**Issue by renekragelundpedersen** [Dietermartens/UVDesk-Docker#2]
Hi, just tried this docker setup and it worked perfectly until i changed to the prod environment in the compose file.
Apparently this has been an issue, that should have been fixed with the latest builds of the uvdesk.

Is it possible to get the newest build of uvdesk in this image?

https://github.com/uvdesk/core-framework/issues/310

**Comment by KccProject** [comment]
Same issue with me...

Uncaught RuntimeException: Unable to write in the cache directory (/var/www/html/var/cache/prod) in /var/www/html/vendor/symfony/http-kernel/Kernel.php:656 Stack trace: #0 /var/www/html/vendor/symfony/http-kernel/Kernel.php(555): Symfony\Component\HttpKernel\Kernel->buildContainer() #1 /var/www/html/vendor/symfony/http-kernel/Kernel.php(133): Symfony\Component\HttpKernel\Kernel->initializeContainer() #2 /var/www/html/vendor/symfony/http-kernel/Kernel.php(193): Symfony\Component\HttpKernel\Kernel->boot() #3 /var/www/html/public/index.php(25): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request)) #4 {main} thrown in /var/www/html/vendor/symfony/http-kernel/Kernel.php on line 656

**Comment by lazyest** [comment]
maintainer has gone it seems?

**Comment by Dietermartens** [comment]
I've updated the build file with the latest version and an upgrade to php 8.3. Can you verify if your problems are resolved?

**Comment by lazyest** [comment]
just from scratch I see

docker-compose exec -T uvdesk php bin/console uvdesk:configure-helpdesk


  Examining helpdesk setup for any configuration issues:

  [-] Establishing a connection with database server

In Setup.php line 254:
                      
  Connection refused  
                      

uvdesk:configure-helpdesk



Also on manual install I see

You meet 2 out of 3 config files permission.

Issue can be resolved by simply[ enabling read/write permissions for your files under config/packages folder of your project.](https://www.uvdesk.com/en/blog/open-source-helpdesk-installation-on-ubuntu-uvdesk/)
Hide details

    uvdesk.yaml read/write file permission is enabled.
    uvdesk_mailbox.yaml read/write file permission is enabled.

**Comment by lazyest** [comment]
docker-compose exec -T uvdesk ls -la config
total 32
drwxrwxrwx  4 docker docker 4096 Sep  5 11:41 .
drwxr-xr-x 15 docker docker 4096 Sep  5 11:46 ..
-rw-r--r--  1 docker docker 1664 Sep  5 09:21 bundles.php
drwxr-xr-x  4 docker docker 4096 Sep  5 11:42 packages
-rw-r--r--  1 docker docker  184 Sep  5 09:21 preload.php
drwxr-xr-x  2 docker docker 4096 Sep  5 11:41 routes
-rw-r--r--  1 docker docker  104 Aug 29 13:49 routes.yaml
-rw-r--r--  1 docker docker 1649 Aug 29 13:49 services.yaml


I see its not 775

also I've installed mysql client inside container and checked, 

docker@b13c8cf6dbb0:/var/www/html$ mysql -h db
ERROR 1045 (28000): Access denied for user 'docker'@'172.17.0.4' (using password: NO)

its not Connection Refused ;) So I assume its something wrong with file access mode

**Comment by lazyest** [comment]
well, I've set 775 to config and run setup manually from web, seems like db is somehow related

**Comment by Dietermartens** [comment]
Hi @lazyest,

I've validated the setup locally with the following config:
`
networks:
  public:
    name: proxy
    external: false

volumes:
  app:
  mysql:

services:
  uvdesk:
    image: dietermartens/uvdesk
    environment:
      # installation in dev, change it after installation to prod
      - APP_ENV=prod
      - APP_SECRET=
      - TZ=Europe/Brussels
      - APP_TIMEZONE=Europe/Brussels
      - APP_CURRENCY=EUR
      - CRON_USER1=root
      - CRON_SCHEDULE1=*/5 * * * *
      - CRON_COMMAND1=cd /var/www/html && php bin/console uvdesk:refresh-mailbox info@domain.tld support@domain.tld
    restart: always
    extra_hosts:
      - "{uvdesk.domain.tld}:127.0.0.1"
    ports:
      - 80:80
    networks:
      - public
    volumes:
      - app:/var/www/html
    links:
      - db

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootPassword
    networks:
      - public
    volumes:
      - mysql:/var/lib/mysql
`

With the db and uvdesk in the same network the database config works. Make sure to run the setup in "dev" mode, after the installation is complete you can change it to prod. 

If you run into trouble during the installation (when you changed the APP_ENV) you can run this command in the CLI and try the installation procedure again: `a2enmod rewrite`. The same goes for then the installation is stuck.

**Comment by lazyest** [comment]
On earlier build there was a possibility to set
      - DATABASE_URL=mysql://uvdesk:password@db:3306/uvdesk
and then do 

docker-compose exec uvdesk php bin/console uvdesk:configure-helpdesk

and this installed everything :) also there was a way to configure admin username, mail sending provider, everything.

now I have connection refused on uvdesk:configure-helpdesk try

  [-] Establishing a connection with database server

In Setup.php line 254:
                      
  Connection refused  
                      

uvdesk:configure-helpdesk

at the same time I've installed mysql-client inside container and can see this:

root@uvdesk:/opt/uvdesk# docker-compose exec uvdesk mysql -h db
ERROR 1045 (28000): Access denied for user 'docker'@'172.17.0.5' (using password: NO)

so I think issue is ignoring DATABASE_URL environment variable. Can you please take a look on this?

**Comment by Dietermartens** [comment]
@lazyest You need to fix the database connection so that you can use mysql to connect from the CLI to the database from the uvdesk container. When this works you need to validate if UVDesk itself can connect to the database. The fact that you cannot connect using the CLI means there is a networking issue/ connection, unrelated to the php or uvdesk. 

1. Try to login with `docker exec -ti [CONTAINER_ID] bash`
2. install mysql client
3. try to connect to the database using: `mysql -h [HOST] -u [USER] -p`

**Comment by lazyest** [comment]
that's in particular thing I've done :) I think I've investigated everything, its ignoring env variable so trying to connect to default localhost and that's why connection refused appeared

**Comment by lazyest** [comment]
As you can see, there is not connection refused but wrong password by mysql client, its OK, connectivity is fine. Please check env variable, maybe it was somehow renamed occasionally?

**Comment by lazyest** [comment]
I've investigated more

with -vvv it returned me   [-] Establishing a connection with database server

In Setup.php line 254:
                      
  [RedisException]    
  Connection refused  

Redis? I'm pretty surprised

**Comment by lazyest** [comment]
Yes, I disabled redis php module by phpdismod redis and advanced further ;) So this can be or somehow documented, or maybe fixed by default, thanx

**Comment by Dietermartens** [comment]
@lazyest 

As you can see we do not have any config in the docker setup. So i guess you will need to take this up with the uvdesk team. Feel free to create a PR if you have a permanent fix.
